modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "spawn_notification"
version = "1.5-forge-1.1.0"
displayName = "Cobblemon Spawn Notification"
description = '''
When a Legendary and/or Shiny Pokemon shows up, a message is broadcast to all players on the server.
'''

[[dependencies.spawn_notification]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.spawn_notification]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spawn_notification]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5.0,1.6.0)"
ordering = "NONE"
side = "BOTH"
